### ISSUE TITLE
Ask about flake + cachix

### ISSUE THREAD

**Issue by hmanhng** [linuxmobile/kaku#5]
I want to build a package in flake like `anyrun` and upload it to `cachix` with `github action` before building it on the local machine.
As I know I can build all flake with 
```nix
nix build -L '.#nixosConfigurations.laptop.config.system.build.toplevel'
```
Doing so takes up too much space and errors occur. Is there a way to build only 1 packags in my flake?
Here is my github action file
```yaml
name: build-and-cache
"on":
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Create Dir for Mounting moar Disk Space ❄️ "
        run: |
          sudo mkdir /nix
      - name: "Maximize Disk Space"
        uses: easimon/maximize-build-space@v8
        with:
          build-mount-path: /nix
          remove-android: true
          remove-codeql: true
          remove-docker-images: true
          remove-dotnet: true
          remove-haskell: true

      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: "Install Cachix ❄️ "
        uses: cachix/cachix-action@v12
        with:
          name: hmanhng
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community, hyprland, hmanhng, anyrun

      - name: Set default git branch (to reduce log spam)
        run: git config --global init.defaultBranch tmpfs

      - name: Validate Flakes
        run: nix flake check --print-build-logs --accept-flake-config

      - name: "Build NixOS config ❄️ "
        run: |
          nix build -L '.#nixosConfigurations.laptop.config.system.build.toplevel'
```
